# -*- coding: utf-8 -*-
"""iot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qcAqdTUzbJH0GIeN_ju9IG6QjLFLrtpP
"""

from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
import pandas as pd
from pandas.io.json import json_normalize
import json
import matplotlib.pyplot as plt

url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'
service_key='olagdtOMmxo/SGViApo7KMrckkJA4LTnnQuWlhzeWv0+3gHV6RA8o+YAKxvQBy+juX4G4aAfN2Pl29K69jWi8w=='

queryParams = '?' + urlencode({quote_plus('ServiceKey') : service_key,
                               quote_plus('pageNo') : '1',
                               quote_plus('numOfRows') : '720',
                               quote_plus('dataType') : 'JSON',
                               quote_plus('dataCd') : 'ASOS', 
                               quote_plus('dateCd') : 'HR', 
                               quote_plus('startDt') : '20220101', #시작날짜
                               quote_plus('startHh') : '01',
                               quote_plus('endDt') : '20220131', #종료날짜
                               quote_plus('endHh') : '01',
                               quote_plus('stnIds') : '99' }) # 지역코드

# 서울 108 , 파주 99

response = urlopen(url + queryParams)
json_api = response.read().decode("utf-8")

json_file = json.loads(json_api)
df=json_normalize(json_file['response']['body']['items']['item'])

df

df['tm']=pd.to_datetime(df['tm'])
df['ts'] = pd.to_numeric(df['ts'], downcast='float')

fig = plt.figure(figsize=(14,6))
ax = plt.subplot(1,1,1)

ax.plot(df['tm'],df['ts'],color='r',lw=1.5,alpha=0.7)
ax.set_ylabel('temp', fontweight='bold', fontsize=12)
ax.set_xlabel('date', fontweight='bold', fontsize=12)
ax.set_title('temp data', fontweight = 'bold',fontsize = 14)